[package]
name = "chainql"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.14", features = ["derive"] }
frame-metadata = "15.0.0"
hex = "0.4.3"
jrsonnet-evaluator = { git = "https://github.com/CertainLach/jrsonnet.git" }
jrsonnet-cli = { git = "https://github.com/CertainLach/jrsonnet.git" }
jrsonnet-gcmodule = "0.3.4"
jsonrpsee = { version = "0.15.0", features = ["macros", "ws-client"] }
parity-scale-codec = { version = "3.1.5", features = ["derive"] }
scale-info = "2.1.2"
serde = "1.0.140"
serde_json = "1.0.82"
sp-core = "6.0.0"
tokio = { version = "1.20.1", features = ["rt-multi-thread"] }
thiserror = "1.0.31"
